### PR TITLE
Fix for crash when manager is released during upload

### LINKED ISSUE #10: Library crashes when manager is released during upload
The callbacks in managers use `[unowned self]` ([example](https://github.com/JuulLabs-OSS/mcumgr-ios/blob/master/Source/Managers/DFU/FirmwareUpgradeManager.swift#L386)). When the manager is released when a request was sent, the callback will crash as self is `nil`. According to [this](https://stackoverflow.com/a/24320474/2115352) post:

> The difference between `unowned` and `weak` is that `weak` is declared as an Optional while `unowned` is not. By declaring it `weak` you get to handle the case that it might be `nil` inside the closure at some point. If you try to access an `unowned` variable that happens to be `nil`, it **will crash the whole program**. So only use `unowned` when you are positive that variable will always be around while the closure is around.

Two changes are needed:
1. Change unowned to weak, to prevent crashing.
2. When upload or download is started, the manager should hole a strong cyclic reference to prevent from being released. The cycle should be broken when upload completed, failed, or was cancelled. This would allow for "start upload and forget" scenario.

Both apply to `FSManager` as well.

### PR DESCRIPTION
**Pull request by philips77**
This PR fixes #10.
CC: @zetokz

### CODE REVIEW

**Comment by philips77** [comment]
The first commit fixes part 1: it weakens the references, so the app should not crash when the manager gets released. Not tested.

**Comment by philips77** [comment]
The second commit adds a cyclic reference that's hold during upload or download. In order to stop the process call `cancel()` instead of simply forgetting the reference to the manager.

**Comment by philips77** [comment]
@zetokz @bgiori any comments?

**Comment by zetokz** [comment]
Looks good to me
@bgiori can you merge it, please?

**Comment by bgiori** [comment]
Approved. I'll let @philips77 decide when to merge. Thanks for all your contributions!

**Comment by philips77** [comment]
Go ahead.

**Pull request merged**
