### PR TITLE
Logging improvements

### PR DESCRIPTION
**Pull request by philips77**
This PR improves logging in the library. The log delegate now works for all managers, not only DFU. By default, the library will not print any logs in the console. Instead, user is responsible for assigning `logDelegate` to the transporter or to any manager that is used.

The `Log` class has been deleted. `Log.Level` is not a standalone enum, called `McuMgrLogLevel`. The log delegate is compatible with the "new" OSLog framework (iOS 10+), which logs into system Console.

Other changes:
1. CBOR received `CustomDebugStringConvertible` to be printed as map.
2. More logging messages added, some fixed or modified.
3. Log level of some messages has been changed.

Breaking changes:
1. `McuMgrBleTransport.init(...)` no longer return optional.
2. `Log` class removed (it was public for some reason).
3. Errors are no longer `CustomStringConvertible`, now they extend `LocalizedError`.
4. `state` property in `McuMgrBleTransport` no longer has public setter.

### CODE REVIEW

**Comment by philips77** [comment]
image
Improved logs as seen in Console app using the Sample App.

**Comment by bgiori** [comment]
These are much needed changes, so thanks for putting in the time and effort!

I love the CBOR extensions to print specific keys differently -- smart stuff.

My main concern is the amount of effort it takes to get access to these logs, as each manager which gets initialized must have its `logDelegate` set independently. I would be more partial to a single global delegate which can be set once and forgotten.

If you have purposefully designed it to have each manager get its `logDelegate` set independently let me know, as this is more of a convenience issue than a correctness one.

Otherwise it looks very good, as always!

Since we are making breaking changes to the transporter, etc. we might want to slip in as many breaking changes as we can before pushing a major release.

**Comment by philips77** [comment]
I can understand setting a `logDelegate` per manager is a bit frustrating, but:
1. It's just 1 line of code per each :)
2. Global static log delegate would not look good, and could lead to some memory leaks, I think.
3. With separate delegates it's more flexible. For example, apps may skip logging low level messages when DFU is in progress, as there's a loooot printed (4 logs per one packet sent). At the same time another manager may have the filter disabled.
4. Not many apps will have multiple managers, like the sample app. Mostly just firmware upgrade delegate will be used, which actually sets the `logDelegate` of 2 inner delegates.

**Comment by bgiori** [comment]
Fair enough! 

My final request (sorry I failed to mention this in the original comment) would be to add a heading to the README to briefly describe how to set the logging delegate.

Thanks again!

**Comment by philips77** [comment]
I've updated Readme and added CBOR.Tag parsing, also tested it on some simple tags.
Should we release now, or do you have any more ideas related to logging or other features you want in?

**Comment by philips77** [comment]
@bgiori How about a release today with all the recent PRs merged?

**Pull request merged**
