### PR TITLE
Fixes centralManager delegate being set to nil on disconnect

### LINKED ISSUE #28: DFU is broken
Hey,
The DFU is broken on the reset/confirm stage. This is due to the `centralManager.delegate` being set as `nil` on `McuMgrBleTransport.centralManager(_ central:didDisconnectPeripheral:error:)`.

Because the `delegate` is set to nil after the `reset` is sent (on disconnect), when the peripheral reconnects there's no callback to complete the `confirm` state and thus the DFU is stuck until a timeout occurs.

To fix this we either need to stop setting the `delegate` to nil on disconnect or we need to re-set the `delegate` before `centralManager.connect(...)` is called. I think the best solution is probably setting the `delegate` just before connecting, to avoid getting any unwanted callbacks.

I've submitted PR #29 to fix this issue.

### PR DESCRIPTION
**Pull request by lm2s**
Fixes #28

### CODE REVIEW

**Comment by philips77** [comment]
After #27, the central manager delegate needs to observe the manager's state to retrieve the `CBPeripheral` instance.
Are you sure the `targetPeripheral` can't be `nil` at this point and is valid, even if Bluetooth is off/restarted?

**Comment by lm2s** [comment]
This issue seems unrelated to #27. In this case the peripheral is already valid (all the upload process has occurred). 

What happens is that centralManager.delegate is set to nil on the `CBCentralManagerDelegate.centralManager(_ central: CBCentralManager, didDisconnectPeripheral peripheral: CBPeripheral, error: Error?)` and never re-set to `self`.

So when, after uploading, the McuMgrBleTransport sends the reset command and the peripheral disconnects. McuMgrBleTransport is no longer notified of the peripheral being reconnected and stays stuck.

If you put a breakpoint on McuMgrBleTransport.swift:268 (on the .disconnected case), you see that centralManager.delegate is nil when centralManager.connect(targetPeripheral) is called.

**Comment by philips77** [comment]
Yes, I understand, but I'm wondering wouldn't it be better to just remove the set to `nil`. For example, is the `CBPeriphheral` instance valid after restarting Bluetooth. Let's say someone was updating the device and switched Bluetooth in between, causing the device to disconnect. Then enables it again and clicks Continue. Will the previous instance work, or a new one would have to be retrieved on `.poweredOn` state change. I don't know, actually. Also, will it be consistent for the future versions of iOS? I think it's safer to assume that for each "power up" a new peripheral instance may be needed, although I'm pretty sure your commit will work for now.

**Comment by lm2s** [comment]
Ah sorry, I didn't understood. 

Initially I thought about removing the set to nil, but ended up not doing it because I wasn't sure if there was a particular reason as to why it exists.

AFAIK the peripheral will be valid between CBCentralManager state changes, but I agree that it'll probably be safer to go with your option.

I'll adjust the PR.

**Comment by lm2s** [comment]
@bgiori yes, with this change DFU is working properly again.

**Pull request merged**
